name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js 16
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies using npm ci
      - name: Install dependencies
        run: npm ci

      # Run Tests
      - name: Run Tests
        run: npm run test

      # Build the project
      - name: Build the project
        run: npm run build
